### ISSUE TITLE
Roadmap 0.4

### ISSUE THREAD

**Issue by dyoder** [dashkite/joy#3]
*   [ ] Possibly rename `normalize` so we can use that to wrap `String::normalize`.
*   [ ] Test browser build using Mimic.
    *   [ ] Confirm that we can avoid loading everything via import map.
